name: Django CI/CD Pipeline 
on:
    push:
        branches:
            - feature/gh-actions-test
    pull_request:
        branches:
            - feature/gh-actions-test
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            
            - name: Install dependencies
              run: |
                    cd backend
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            - name: Run tests
              run: |
                    cd backend
                    python manage.py test
